In [1]:
#Q1

In [2]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
documentA = 'sunshine state enjoy sunshine'
documentB = 'brown box jump high , brown box run'
documentC = 'sunshine state fox run fast'

In [4]:
bagOfWordsA = documentA.split(' ')
bagOfWordsB = documentB.split(' ')
bagOfWordsC = documentC.split(' ')

In [5]:
uniqueWords = set(bagOfWordsA).union(set(bagOfWordsB)).union(set(bagOfWordsC))

In [6]:
numOfWordsA = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsA:
    numOfWordsA[word] += 1
numOfWordsB = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsB:
    numOfWordsB[word] += 1
numOfWordsC = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsC:
    numOfWordsC[word] += 1

In [7]:
def computeTF(wordDict, bagOfWords):
    tfDict = {}
    bagOfWordsCount = len(bagOfWords)
    for word, count in wordDict.items():
        tfDict[word] = count / float(bagOfWordsCount)
    return tfDict

In [8]:
tfA = computeTF(numOfWordsA, bagOfWordsA)
tfB = computeTF(numOfWordsB, bagOfWordsB)
tfC = computeTF(numOfWordsC, bagOfWordsC)

In [9]:
def computeIDF(documents):
    import math
    N = len(documents)
    
    idfDict = dict.fromkeys(documents[0].keys(), 0)
    for document in documents:
        for word, val in document.items():
            if val > 0:
                idfDict[word] += 1
    
    for word, val in idfDict.items():
        idfDict[word] = math.log(N / float(val))
    return idfDict

In [10]:
idfs = computeIDF([numOfWordsA, numOfWordsB, numOfWordsC])

In [11]:
def computeTFIDF(tfBagOfWords, idfs):
    tfidf = {}
    for word, val in tfBagOfWords.items():
        tfidf[word] = val * idfs[word]
    return tfidf

In [12]:
tfidfA = computeTFIDF(tfA, idfs)
tfidfB = computeTFIDF(tfB, idfs)
tfidfC = computeTFIDF(tfC, idfs)

In [13]:
df = pd.DataFrame([tfidfA, tfidfB, tfidfC])
df

fast      high       fox     brown       box  sunshine       run  \
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.202733  0.000000   
1  0.000000  0.137327  0.000000  0.274653  0.274653  0.000000  0.050683   
2  0.219722  0.000000  0.219722  0.000000  0.000000  0.081093  0.081093   

       jump     state         ,     enjoy  
0  0.000000  0.101366  0.000000  0.274653  
1  0.137327  0.000000  0.137327  0.000000  
2  0.000000  0.081093  0.000000  0.000000

In [15]:
#Q2

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
vectorizer = CountVectorizer()
docs = np.array(['sunshine state enjoy sunshine',
                 'sunshine state fox run fast'])

bag = vectorizer.fit_transform(docs)
print(vectorizer.get_feature_names_out())
print(vectorizer.vocabulary_)
print(bag.toarray())

['enjoy' 'fast' 'fox' 'run' 'state' 'sunshine']
{'sunshine': 5, 'state': 4, 'enjoy': 0, 'fox': 2, 'run': 3, 'fast': 1}
[[1 0 0 0 1 2]
 [0 1 1 1 1 1]]


In [26]:
from sklearn.metrics.pairwise import cosine_similarity
standardData = docs.reshape(1,-1)
X = CountVectorizer().fit_transform(docs).toarray()
print(X)
cos_sim_1_2 = cosine_similarity([X[0, :], X[1, :]])
print('Cosine Similarity = \n',cos_sim_1_2 )

[[1 0 0 0 1 2]
 [0 1 1 1 1 1]]
Cosine Similarity = 
 [[1.         0.54772256]
 [0.54772256 1.        ]]
