In [1]:
#Question2

In [2]:
from sklearn import preprocessing
from sklearn import metrics, model_selection
import pandas as pd

data = pd.read_csv('gender-prediction.csv')
data.head()

labels = preprocessing.LabelEncoder()

beard_new = labels.fit_transform(data.beard)
hair_length_new = labels.fit_transform(data.hair_length)
scarf_new= labels.fit_transform(data.scarf)
eye_color_new = labels.fit_transform(data.eye_color)
gender_new = labels.fit_transform(data.gender)


In [3]:
df = data.drop(['beard','hair_length','scarf','eye_color','gender'],axis=1)
df

height  weight  shoe_size
0       71     176         44
1       68     165         41
2       62     132         37
3       65     138         38
4       70     197         43
..     ...     ...        ...
75      65      99         39
76      61      98         37
77      67     119         40
78      70     190         43
79      62     142         37

[80 rows x 3 columns]

In [4]:
X = list(zip(df.height, df.weight, beard_new, hair_length_new, df.shoe_size, scarf_new, eye_color_new))
y = gender_new


In [5]:
#Random Forest

In [6]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,f1_score
from sklearn.ensemble import RandomForestClassifier

In [7]:
#67%-33% split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,random_state=42)
rfc = RandomForestClassifier(n_estimators= 50)
rfc.fit(X_train, y_train)
pred = rfc.predict(X_test)

print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))
print("Accuracy: ", accuracy_score(y_test,pred))

[[11  1]
 [ 0 15]]


              precision    recall  f1-score   support

           0       1.00      0.92      0.96        12
           1       0.94      1.00      0.97        15

    accuracy                           0.96        27
   macro avg       0.97      0.96      0.96        27
weighted avg       0.97      0.96      0.96        27

Accuracy:  0.9629629629629629


In [8]:
#80%-20% split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,random_state=42)
rfc = RandomForestClassifier(n_estimators= 50)
rfc.fit(X_train, y_train)
pred = rfc.predict(X_test)

print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))
print("Accuracy: ", accuracy_score(y_test,pred))

[[7 0]
 [0 9]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         9

    accuracy                           1.00        16
   macro avg       1.00      1.00      1.00        16
weighted avg       1.00      1.00      1.00        16

Accuracy:  1.0


In [9]:
#Svm

In [10]:
from sklearn.svm import SVC

In [11]:
model = SVC()

In [12]:
#67%-33% split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,random_state=42)
model.fit(X_train,y_train)
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))


[[ 9  3]
 [ 4 11]]
              precision    recall  f1-score   support

           0       0.69      0.75      0.72        12
           1       0.79      0.73      0.76        15

    accuracy                           0.74        27
   macro avg       0.74      0.74      0.74        27
weighted avg       0.74      0.74      0.74        27



In [13]:
#80%-20% split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,random_state=42)
model.fit(X_train,y_train)
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[5 2]
 [4 5]]
              precision    recall  f1-score   support

           0       0.56      0.71      0.63         7
           1       0.71      0.56      0.63         9

    accuracy                           0.62        16
   macro avg       0.63      0.63      0.63        16
weighted avg       0.64      0.62      0.63        16



In [14]:
#Multilayer Perceptron 

In [15]:
from sklearn.neural_network import MLPClassifier

In [16]:
model = MLPClassifier()

In [17]:
#67%-33% split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,random_state=42)
model.fit(X_train,y_train)
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[10  2]
 [ 1 14]]
              precision    recall  f1-score   support

           0       0.91      0.83      0.87        12
           1       0.88      0.93      0.90        15

    accuracy                           0.89        27
   macro avg       0.89      0.88      0.89        27
weighted avg       0.89      0.89      0.89        27



F:\anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [18]:
#80%-20% split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,random_state=42)
model.fit(X_train,y_train)
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

F:\anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[[5 2]
 [1 8]]
              precision    recall  f1-score   support

           0       0.83      0.71      0.77         7
           1       0.80      0.89      0.84         9

    accuracy                           0.81        16
   macro avg       0.82      0.80      0.81        16
weighted avg       0.81      0.81      0.81        16



In [19]:
#dropping beard and scraf

In [20]:
X_new = list(zip(df.height, df.weight, hair_length_new, df.shoe_size, eye_color_new))

In [21]:
#random Forest

In [22]:
#80%-20% split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,random_state=42)
rfc = RandomForestClassifier(n_estimators= 50)
rfc.fit(X_train, y_train)
pred = rfc.predict(X_test)

print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))

[[7 0]
 [0 9]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         9

    accuracy                           1.00        16
   macro avg       1.00      1.00      1.00        16
weighted avg       1.00      1.00      1.00        16



In [23]:
#multilayer Perceptron


In [24]:
#80%-20% split
model = MLPClassifier()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,random_state=42)
model.fit(X_train,y_train)
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[3 4]
 [2 7]]
              precision    recall  f1-score   support

           0       0.60      0.43      0.50         7
           1       0.64      0.78      0.70         9

    accuracy                           0.62        16
   macro avg       0.62      0.60      0.60        16
weighted avg       0.62      0.62      0.61        16



In [25]:
#80%-20% split
model = SVC()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,random_state=42)
model.fit(X_train,y_train)
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[5 2]
 [4 5]]
              precision    recall  f1-score   support

           0       0.56      0.71      0.63         7
           1       0.71      0.56      0.63         9

    accuracy                           0.62        16
   macro avg       0.63      0.63      0.63        16
weighted avg       0.64      0.62      0.63        16



In [26]:
#Question 3

In [27]:
import pandas as pd
import numpy as np
import time
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import LeavePOut
from sklearn import preprocessing
from sklearn.model_selection import cross_val_predict, cross_val_score

In [29]:
model= DecisionTreeClassifier()
X_pp = preprocessing.StandardScaler().fit(X).transform(X)

sss = StratifiedShuffleSplit(n_splits = 4, test_size = 0.5, random_state=1)
sss.get_n_splits(X_pp, y)

f1_scores = []

for train_index, test_index in sss.split(X_pp, y):
    X_train, X_test = X_pp[train_index], X_pp[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    model.fit(X_train, y_train)
    prediction = model.predict(X_test)

    f1_scores.append(f1_score(y_test, prediction))    

print("Average F1 Score:", (sum(f1_scores) / len(f1_scores)))

Average F1 Score: 0.9569051204144372


In [33]:
lpo = LeavePOut(1)
lpo.get_n_splits(X, y)
f1_score = cross_val_score(model, X, y, scoring = "f1", cv = lpo)

print("Average F1 Score:", (sum(f1_scores) / len(f1_scores)))

Average F1 Score: 0.9569051204144372


F:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
F:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
F:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
F:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetri

In [34]:
#Question 4

In [35]:
from sklearn.naive_bayes import GaussianNB  

In [36]:
data = pd.read_csv('question4.csv')
data.head()


height  weight beard hair_length  shoe_size scarf eye_color  gender
0      71     176   yes       short         44    no     black    male
1      68     165    no        bald         41    no     black    male
2      62     132    no      medium         37   yes      blue  female
3      65     138    no        long         38    no      gray  female
4      70     197   yes      medium         43    no      gray    male

In [37]:
gb = data.drop(['beard','hair_length','scarf','eye_color','gender'],axis=1)
x = list(zip(gb.height, gb.weight, beard_new, hair_length_new, gb.shoe_size, scarf_new, eye_color_new))
Y = gender_new

In [38]:
model = GaussianNB() 
x_train, x_test, Y_train, Y_test = train_test_split(x, Y, test_size=0.33,random_state=42)
model.fit(x_train,Y_train)
model.fit(x_train, Y_train)  
predictions = model.predict(x_test)
print(confusion_matrix(Y_test,predictions))
print(classification_report(Y_test,predictions))
print("Accuracy =", accuracy_score(Y_test, predictions))

[[10  2]
 [ 0 15]]
              precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.88      1.00      0.94        15

    accuracy                           0.93        27
   macro avg       0.94      0.92      0.92        27
weighted avg       0.93      0.93      0.92        27

Accuracy = 0.9259259259259259
